name: Run Unit Tests

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |
          pip install coverage
          for day in {1..14}; do
            coverage run --append -m unittest 2022.Day${day}.main
          done
          # coverage run --append -m unittest Day15.main
          coverage report -m
