name: run-tests
      
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          python3 -m unittest Day4.main
          python3 -m unittest Day5.main
